[package]
name = "bubbel-bath"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.1.0", features = ["postgres"] }
password-hash = "0.5"
bcrypt-pbkdf = "0.10"
